typography_spectrum: 0.47434
color:
  brandColors:
    - '#000000'
    - '#fb8dfe'
    - '#efc1ef'
    - '#9a5899'
    - '#fa63fa'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6041
analytics:
  google: null
  facebook: null
  twitter: null
name: EROTICA-The Psychology of Perfect 10s
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    url: 'http://thegrid.io/erotica'
    type: external
  - name: Podcasts
    url: 'http://sexi.com'
    type: external
  - name: Sex Kitten Programming
    url: 'http://sex.com'
    type: external
  - name: Girls
    url: 'http://sxy.com'
    type: external
  - name: Our Experts
    url: ' thegrid.ai/erotica'
    type: external
favicon: null
title: POP 101
purpose: []
