name: EROTICA-The Psychology of Perfect 10s
favicon: null
layout_spectrum: 0.6041
typography_spectrum: 0.47434
title: POP 101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#ffffff'
    - '#b3b3b3'
    - '#2f2f2f'
    - '#727272'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
