name: EROTICA-The Psychology of Perfect 10s
favicon: null
layout_spectrum: 0.6041
typography_spectrum: 0.47434
title: POP 101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#df93b9'
    - '#6f6f6d'
    - '#873f43'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
