name: EROTICA-The Psychology of Perfect 10s
favicon: null
layout_spectrum: 0.6041
typography_spectrum: 0.47434
navigation:
  - name: Home
    url: 'http://thegrid.io/erotica'
    type: external
  - name: Community Experts
    url: 'http://sexy.com'
    type: external
  - name: The Principles of Lust
    url: 'http://sexie.com'
    type: external
  - name: Sex Kitten Programming
    url: 'http://sex.com'
    type: external
  - name: Perfect 10 Programming
    url: ' thegrid.ai/erotica'
    type: external
title: The Psychology of Perfect 10s
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fb8dfe'
    - '#efc1ef'
    - '#9a5899'
    - '#fa63fa'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
